### ISSUE TITLE
[D000623] Rep. Mark DeSaulnier

### ISSUE THREAD

**Issue by rshorey** [unitedstates/contact-congress#1370]
Newly elected to 114th congress

**Comment by j-ro** [comment]
tested and working

**Comment by Hainish** [comment]
This isn't working with poltergeist for me, but *is* working with watir.  Are you encountering this as well @j-ro?

**Comment by j-ro** [comment]
yep, needs watir. There's a bunch like that -- anywhere you see in the history me removing the double click, that needs watir.

See https://github.com/EFForg/congress-forms/issues/54 -- I'd like to add a flag to each yaml, but we'd have to decide on congress-forms as a reference system re: the discussion here: https://github.com/unitedstates/contact-congress/pull/1402

**Comment by Hainish** [comment]
I'd rather have no forms *require* `watir`.  The reason is that watir is a huge memory hog.  I'm trying to get to the bottom of why exactly it's messing up with `phantomjs`

**Comment by j-ro** [comment]
So, a double click on the submit button will cause this one to work. I really don't know why, but that's the way I got them to work without watir. However, that messes up Sunlight's non-congress-forms implementation, so it was removed in favor of watir.

But if you find another way, great! I tried a ton of things, waiting, finding, etc... but couldn't get it to work.

**Comment by Hainish** [comment]
I think if anything, there's no reason why we can't have a `wedge` repo that describes which driver should be used for different members.  I'm not sure about including it in the YAML, I think we should keep the YAML files as agnostic as possible to the implementation.  But some really small repo like `congress-forms-preferred-drivers` could be used, to separate out the `congress-forms` hard logic of filling forms from the nitty-gritty of what works where.

**Comment by j-ro** [comment]
I guess the issue is, because the implementations are so different, I don't feel being agnostic is really possible. When do we mark forms as passing? When one person's system works? Most of sunlight's recent commits need fixes for it to work with congress-forms, for example.

So yeah, a small public repo would help so we could quickly see if the form is passing with watir, but there are larger issues at play.

Anyway, see https://github.com/unitedstates/contact-congress/commits/01038bee9487a7cba5e69960db6579fa0ad365b5/members/E000294.yaml for what I've tried to get these to work before resorting to watir.

**Comment by Hainish** [comment]
For this MoC I'm not having a problem of the form not submitting.  I'm having a problem of it submitting, but being brought to a page which is not the "thank you" page that I see with `watir`.  Pretty crazy stuff.

**Comment by j-ro** [comment]
yep, there's a few like that, though less than the not submit. It's probably a related issue, since watir is the fix for all of them. I couldn't find anything in the HTML that was really different between ones that worked and ones that didn't. It was certain themes, so maybe there's something in the CSS or JS that's doing it, but I couldn't figure it out, and the screenshots weren't helpful.

**Comment by Hainish** [comment]
works fine with capybara_webkit, added it to the array

**Comment by j-ro** [comment]
oh, my mistake -- these are ones I use webkit on, not watir. Sorry about the confusion!
