### ISSUE TITLE
[S000320] Sen. Richard Shelby

### ISSUE THREAD

**Issue by konklone** [unitedstates/contact-congress#162]
Sen. Richard Shelby:
http://www.shelby.senate.gov

Likely contact form URL to start with:
http://www.shelby.senate.gov/public/index.cfm/emailsenatorshelby

**Comment by Hainish** [comment]
No quotes allowed in the $MESSAGE body

**Comment by j-ro** [comment]
That's the first I've heard of this...lots of senate forms do some fuzzy "hack" searching and don't like messages with links and such, but quotes?

Anyway, javascript would be useful here, if that's what's going on.

**Comment by gcosta** [comment]
We had the same issue with G000359. Removing quotes from the json data made
it work. Possibly related?

**Comment by j-ro** [comment]
I'm sure this security feature is Senate-wide. I'm also fairly certain it's based on IP reputation (whether its triggered or not), which can lead to full blocks like we're hit with at the moment.

I'm really not sure fixing this, even with javascript, is the way to go, since at least as far as I've been able to tell, this doesn't get triggered every time. For example, using my home computer, I can submit a message with quotes.

**Comment by Hainish** [comment]
I wonder if the entire senatorial form submission system is protected by an
overzealous application-layer IPS like MOD_SECURITY.  We should check other
senate forms.

**Comment by j-ro** [comment]
I'm nearly certain it is. An Akamai firewall I believe.
